from __future__ import annotations

import logging
from pathlib import Path

import pandas as pd

from .features import build_features
from .sections import SECTIONS, Section

log = logging.getLogger("vidscreen")
FILES = {"main": "relevant_videos.csv", "confident": "relevant_confident_videos.csv"}
FEATURE_FILES = {"main": "relevant_features.csv", "confident": "relevant_confident_features.csv"}
DEFAULT_SECTIONS = ["quality", "features", "overview", "duration", "views", "engagement"]


def write_report(ds: str, d: pd.DataFrame, sections: list, out: Path) -> Path:
    desc = {"main": "the main relevant dataset (all videos judged relevant)", "confident": "the confident subset (human-labeled or confident-zone relevant videos only)"}[ds]
    L = [f"# Exploratory data analysis: {ds} dataset", "",
         f"Dataset: {desc}. {len(d):,} videos ({', '.join(f'{p} {(d.platform == p).sum():,}' for p in ('youtube', 'tiktok'))}). Collection date used as the reference date: {d['reference_date'].iloc[0]}.",
         "All numbers in this report are generated by `scripts/run_eda.py` from the data; nothing is typed by hand.",
         "Statistical tests treat videos as independent, although some creators contribute many videos, so p-values are optimistic; effect sizes and confidence intervals are therefore reported, and the robustness step repeats the key results with a cap on videos per creator.", ""]
    for sec in sections:
        L += [f"## {sec.title}", "", sec.intro, ""]
        L += [f"- {f}" for f in sec.findings] + [""]
        for fig in sec.figures:
            L += [f"![{fig}](figures/{fig})", ""]
        if sec.tables:
            L += ["Tables: " + ", ".join(f"`tables/{t}`" for t in sec.tables), ""]
        L += [f"*Note: {n}*" for n in sec.notes] + [""]
    path = out / "EDA_report.md"
    path.write_text("\n".join(L), encoding="utf-8")
    return path


def run_eda(settings, datasets=("main", "confident"), sections=None, out_root: Path = None) -> dict:
    sections = sections or DEFAULT_SECTIONS
    out_root = Path(out_root) if out_root else settings.root / "reports" / "eda"
    done = {}
    for ds in datasets:
        src = settings.final_dir / FILES[ds]
        if not src.exists():
            log.warning("Skipping %s: %s not found", ds, src)
            continue
        raw = pd.read_csv(src, dtype={"video_id": str}, encoding="utf-8-sig")
        log.info("[%s] building features for %d videos ...", ds, len(raw))
        d = build_features(raw)
        d.to_csv(settings.final_dir / FEATURE_FILES[ds], index=False, encoding="utf-8-sig")
        out = out_root / ds
        out.mkdir(parents=True, exist_ok=True)
        secs = []
        for name in sections:
            if name not in SECTIONS:
                raise SystemExit(f"Unknown section '{name}'. Available: {', '.join(SECTIONS)}")
            log.info("[%s] section: %s", ds, name)
            secs.append(SECTIONS[name](d, out))
        done[ds] = write_report(ds, d, secs, out)
        log.info("[%s] report: %s", ds, done[ds])
    return done
